version: "3"
services:
  zookeeper:
    # the configuration manager
    hostname: zookeeper
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  nifi:
    image: apache/nifi:latest
    ports:
      - 8080:8080
      - 8000:8000
    depends_on:
      - zookeeper
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
      - NIFI_SENSITIVE_PROPS_KEY=MySecureKey123!
    # volumes:
    #   - ./nifi_data:/opt/nifi/nifi-current/database_repository
    #   - ./nifi_flow:/opt/nifi/nifi-current/flowfile_repository
    #   - ./nifi_content:/opt/nifi/nifi-current/content_repository
